### ISSUE TITLE
Impossible de démarrer l'application

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#1]
J’ai pull la dernière version de Dispatcher et quand j’essaie de démarrer l’app, que ce soit avec MAMP ou direct avec le serveur PHP intégré, ça me donne une erreur qui m’empêche de démarrer l’app.

Quand je start ça avec MAMP, j’obtiens juste une page complètement blanche avec presque aucun HTML dedans.

Quand je start ça avec le serveur intégré ($ php app/console server:run) ça me retourne dans la console :

``` php
PHP Warning:  require_once(/Users/alord/Documents/Sites/dispatcher/app/bootstrap.php.cache): failed to open stream: No such file or directory in /Users/alord/Documents/Sites/dispatcher/app/console on line 10

PHP Fatal error:  require_once(): Failed opening required '/Users/alord/Documents/Sites/dispatcher/app/bootstrap.php.cache' (include_path='.:') in /Users/alord/Documents/Sites/dispatcher/app/console on line 10
```

Let me know!
![capture d ecran 2015-04-09 a 3 27 38 pm](https://cloud.githubusercontent.com/assets/11218493/7075027/f94e928e-decc-11e4-8a8e-618466162db8.png)

**Comment by fREkk** [comment]
Eum bonne question, j'ai pas runner l'app avec la console "intégrée dans
symfony" ou avec MAMP, je sais pas si t'essaye avec xammp ou wamp?

2015-04-09 15:27 GMT-04:00 Antoine Lord <notifications@github.com>:

**Comment by alordmg** [comment]
J'essaie avec Xammp et je te reviens là dessus.

Chez toi y'a aucun problème à runner l'app ? C'est un peu étrange.

**Comment by fREkk** [comment]
Ben jlui ai pas touché depuis hier soir donc non, comme t'as pu voir ça
allait bien

**Comment by alordmg** [comment]
Avec Xammp ça me retourne dans le navigateur : 

``` php
Warning: require_once(/Applications/XAMPP/xamppfiles/htdocs/dispatcher/web/../app/bootstrap.php.cache): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/dispatcher/web/app_dev.php on line 20

Fatal error: require_once(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/dispatcher/web/../app/bootstrap.php.cache' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/dispatcher/web/app_dev.php on line 20
```

**Comment by fREkk** [comment]
Jvais regarder ce soir quand j'arrive chez moi.

2015-04-09 16:11 GMT-04:00 Antoine Lord <notifications@github.com>:

**Comment by alordmg** [comment]
Okay j'ai trouvé @fREkk :+1:

Il fallait que j'update Composer! Il me manquait plein de dépendances.

[Updating Composer](https://getcomposer.org/doc/00-intro.md#using-composer)
