### ISSUE TITLE
Problème requête BD id_ticket

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#24]
Tout de suite après le login avec admin/admin, j'ai eu cette erreur là.

Y'a juste la page /client qui fonctionne.

@fREkk peut-tu regarder ça stp ?

```
An exception occurred while executing '
![screen shot 2015-04-12 at 5 49 30 pm](https://cloud.githubusercontent.com/assets/11218493/7107721/4ae07c90-e13c-11e4-8da8-76fa639fbac2.png)
SELECT t0.id_ticket AS id_ticket1, t0.nom_ticket AS nom_ticket2, t0.description_ticket AS description_ticket3, t0.travaux_ticket AS travaux_ticket4, t0.note_ticket AS note_ticket5, t0.timeStamp_ticket AS timeStamp_ticket6, t0.id_parent_entreprise AS id_parent_entreprise7, t0.id_agent AS id_agent8, t0.id_etat_ticket AS id_etat_ticket9, t0.id_entreprise AS id_entreprise10 FROM ticket t0 WHERE t0.id_parent_entreprise = ?' with params [1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.id_parent_entreprise' in 'field list'
```

**Comment by fREkk** [comment]
Ta BD est pas à jour, jvais regarder si c'est la dernière que j'ai mit sur
le GIT. T'as pas la colonne id_parent_ticket dans la table ticket.

Je te reviens quand j'arrive chez moi!

2015-04-12 16:49 GMT-05:00 Antoine Lord <notifications@github.com>:

**Comment by alordmg** [comment]
Thanks!


 <http://lesmauvaisgarcons.ca/>
 <http://lesmauvaisgarcons.ca/>

**Comment by fREkk** [comment]
Here you go, jvoulais l'ajouter dans GIT mais quand jessaye de pusher j'ai
un 403 Forbidden.

Bonne soirée

2015-04-12 18:54 GMT-04:00 Antoine Lord <notifications@github.com>:

> Thanks!
>
>
> <http://lesmauvaisgarcons.ca/>
> <http://lesmauvaisgarcons.ca/>

**Comment by alordmg** [comment]
Hey yo!

J'suis pas sûr de comprendre, la BD est dans Git ou non ?

Merci de me répondre rapidement, j'dois absolument travailler là dessus ce PM.

**Comment by fREkk** [comment]
Non en piece jointe du dernier email.

Ça me dit que j'ai plus les acces pour pusher, dont know why.

Bonne PM

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Ha ouais j'ai transféré le repo dans mon compte (alordmg) faudrait que tu re-clone le repo avec cette adresse là : ```https://github.com/alordmg/dispatcher.git```si tu veux pouvoir refaire des changements. Sorry j'pensais pas le transfert affecterais tant que ça.

**Comment by alordmg** [comment]
Good!

dispatcher_mg-fonct.sql fonctionne. Merci man
