### ISSUE TITLE
Comment faire la mise en production?

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#25]
Salut @fREkk ,

J'aimerais juste que tu m'éclaire à savoir comment je fais pour mettre l'app en prod quand je vais avoir finalisé les features.

En ce moment chaque push est déployé sur le serveur à cette adresse ```http://45.55.153.230/web/app_dev.php```

C'est pas pressant mais éventuellement j'aimerais que ça ça fonctionne direct sur ``` http://45.55.153.230``` si c'est pas trop compliqué.

Merci

**Comment by fREkk** [comment]
Bonne question, j'avais pas encore travailler en prod. Je l'ai déjà fait
mais jme souviens plus comment :S C'était pas compliquer messemble.

**Comment by alordmg** [comment]
Okay alors voici un récapitulatif : 

- [ ] Héberger sur le serveur la version la plus récente de l'app. (Je m'en charge)
- [ ] Importer la base de donnée (je m'en charge)
- [ ] Mettre l'app en production (à moins que ça doit être fait avant d'être uploadé ?)
- [ ] Mettre à jour les dépendances avec Composer
- [ ] Configurer l'app pour qu'elle soit accessible directement depuis [45.55.153.230](http://45.55.153.230)
- [ ] Créer un accès pour Pier-Luc

**Comment by fREkk** [comment]
Tu n'as qu'a mettre l'app sur un serveur, envoi moi l'adresse et je peux me charger 4 derniers points. 

Oublie pas de vider la base de données avant de l'importer (ou apres a la limite)


Envoyé de mon iPhone

**Comment by alordmg** [comment]
Okay j'ai uploadé les fichiers et j'ai importé la base de donnée.

L'app est dispo à [http://45.55.153.230/web/app_dev.php](http://45.55.153.230/web/app_dev.php)

As-tu besoin des accès FTP/SSH/MySQL/whatever ?

**Comment by fREkk** [comment]
Est-ce que cest les meme que boulet? Aussi non ouais on sait jamais.

Pourrais-tu checker comment updater les dependences de composer? 

Je regarde ça probablement ce soir max demain soir! Jte tiens au courant!

Envoyé de mon iPhone

**Comment by fREkk** [comment]
C'est normal ça : You are not allowed to access this file. Check
app_dev.php for more information. ?

Le 20 avril 2015 14:43, Francis Perreault <franperreault@gmail.com> a écrit
:

> Est-ce que cest les meme que boulet? Aussi non ouais on sait jamais.
>
> Pourrais-tu checker comment updater les dependences de composer?
>
> Je regarde ça probablement ce soir max demain soir! Jte tiens au courant!
>
> Envoyé de mon iPhone
>

**Comment by fREkk** [comment]
"En vous connectant sur app_dev.php, si vous n'êtes pas en local, vous
allez obtenir l'erreur suivante: "You are not allowed to access this file.
Check app_dev.php for more information.". Ajoutez votre IP dans la liste
des IP autorisées en début du fichier app_dev.php pour ne plus avoir
l'erreur."

Le 20 avril 2015 14:45, Francis Perreault <franperreault@gmail.com> a écrit
:

> C'est normal ça : You are not allowed to access this file. Check
> app_dev.php for more information. ?
>
> Le 20 avril 2015 14:43, Francis Perreault <franperreault@gmail.com> a
> écrit :
>
>> Est-ce que cest les meme que boulet? Aussi non ouais on sait jamais.
>>
>> Pourrais-tu checker comment updater les dependences de composer?
>>
>> Je regarde ça probablement ce soir max demain soir! Jte tiens au courant!
>>
>> Envoyé de mon iPhone
>>

**Comment by alordmg** [comment]
J'ai juste carrément désactivé le check de l'adresse IP. Ça va nous éviter du trouble. J'te donne des news si ça marche.

**Comment by alordmg** [comment]
Non les accès sont différents : 

**SSH**
IP : 45.55.153.230
User : root
Pass : c%W3>z8VcM

**FTP**
IP : 45.55.153.230
User : root
Pass : c%W3>z8VcM

**MySQL**
User : root
Pass : ;mgy;vVZ48

**Comment by alordmg** [comment]
Okay la version que j'ai installé sur le serveur, j'essaie d'exécuter http://45.55.153.230/web/app_dev.php et ça me donne une erreur.

![capture d ecran 2015-04-20 a 4 49 19 pm](https://cloud.githubusercontent.com/assets/11218493/7240266/c3cf7736-e77d-11e4-8be0-01f82a3c7da2.png)


J'ai essayer de faire ```composer update``` et ```composer install```. ça me donne une _encore_ une erreur : 

![capture d ecran 2015-04-20 a 4 52 41 pm](https://cloud.githubusercontent.com/assets/11218493/7240257/b51d6112-e77d-11e4-9657-711d7ed63607.png)

J'ai regardé rapidement sur Google et semblerait que c'est un conflit de dépendances.
