### ISSUE TITLE
Impossible de supprimer un client

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#26]
Au clic sur supprimer, aucune confirmation de suppression. Le client en se supprime pas.

Console du navigateur :
```[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (21, line 0)```

**Comment by fREkk** [comment]
C'est quoi l'erreur si t'ouvres l'URL qui te pose probleme?

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Ça me retourne pas d'erreur.

Je clique sur Supprimer, ça me dit « Êtes vous sûr de vouloir supprimer? » je clique Oui et y se passe rien.

**Comment by fREkk** [comment]
T'as un erreur 500 right? Clique sur le lien ça va t'afficher c'est quoi
l'erreur

**Comment by fREkk** [comment]
​Genre en cliquant sur le lien a droite, ça va te rediriger vers une page
avec un erreur symfony

Le 13 avril 2015 14:40, Francis Perreault <franperreault@gmail.com> a écrit
:

> T'as un erreur 500 right? Clique sur le lien ça va t'afficher c'est quoi
> l'erreur
>

**Comment by alordmg** [comment]
Regarde ce que ça fait : https://www.dropbox.com/s/xn359sfry5m5m50/suppression.mov?dl=0

**Comment by fREkk** [comment]
Clique sur le lien a droite de l'erreur genre a droite :
localhost/dispatcher/web/app_dev.php/supprimer/client/1

2015-04-13 14:54 GMT-04:00 Antoine Lord <notifications@github.com>:

**Comment by fREkk** [comment]
De mon côté ça fonctionne.

**Comment by alordmg** [comment]
Si je vais direct dans PHPMyAdmin pour supprimer les deux clients qui restent, ça me sort cette erreur et j'dois t'avouer que je comprend quedalle :

![Erreur MySQL](https://cloud.githubusercontent.com/assets/11218493/7167127/a1bce2c4-e380-11e4-978b-0ca5781e52f7.png)

**Comment by fREkk** [comment]
C'est a cause que tes clients sont utiliser ailleurs, soit dans un ticket ou dans un user. Pour pouvoir deleter quelque chose faut plus qu'un autre objet l'aie en reference. Jsais pas si cest clair?

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Okay je comprend. Merci.
