### ISSUE TITLE
Impossible d'ajouter un ticket

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#30]
Quand j'essaie d'ajouter un ticket, le call AJAX échoue et me retourne : 

```
An exception occurred while executing &#039;INSERT INTO ticket (nom_ticket, description_ticket, travaux_ticket, note_ticket, timeStamp_ticket, id_parent_entreprise, id_agent, id_etat_ticket, id_entreprise) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)&#039; with params [&quot;Je fais un test&quot;, &quot;Encore un test&quot;, &quot;Beaucoup de tests&quot;, null, &quot;2015-04-13 15:33:55&quot;, null, null, 1, 36]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;id_parent_entreprise&#039; cannot be null (500 Internal Server Error)
```

**Comment by fREkk** [comment]
Refactor de la fonction qui ajoute les tickets, elle fonctionne dans mon environnement
--------------------------------

public function ajaxAjouterTicketAction(){
		
		$request = $this->getRequest();
		
		
		
		$idAgent = $request->request->get('agent');
		
		$entrepriseRepo = $this->getDoctrine()
        ->getRepository('dispatcherBundle:Entreprise');
		
		$agentRepo = $this->getDoctrine()
        ->getRepository('dispatcherBundle:Agent');
		
		$agent = $agentRepo->findOneByidAgent($idAgent);
		
		$etatRepo = $this->getDoctrine()
        ->getRepository('dispatcherBundle:EtatTicket');
		
		$etat = $etatRepo->findOneByidEtatTicket(1);
		
		$idEntrepriseCourante = $this->getUser()->getIdEntreprise()->getIdEntreprise();
		$entrepriseCouranteSession = $entrepriseRepo->findOneByidEntreprise($idEntrepriseCourante);
		
		//Gestion du nouveau ticket
		$nomTicket = $request->request->get('nomTicket');
		$description = $request->request->get('description');
		$travail = $request->request->get('travaux');
		
		
		//Gestion entreprise
		$idEntreprise = $request->request->get('idEntreprise');
		
		$nomEntreprise = $request->request->get('entreprise');
		$prenom = $request->request->get('prenom');
		$nom = $request->request->get('nom');
		$telephone = $request->request->get('telephone');		
		$courriel = $request->request->get('courriel');
		
		
		$adresse = $request->request->get('adresse');
		$appt = $request->request->get('appt');
		$ville = $request->request->get('ville');
		$province = $request->request->get('province');
		$codePostal = $request->request->get('codePostal');
		
		$entreprise = new Entreprise();
		$entreprise->setNomEntreprise($nomEntreprise);
		$entreprise->setPrenomcontactEntreprise($prenom);
		$entreprise->setNomcontactEntreprise($nom);
		$entreprise->setTelephoneEntreprise($telephone);
		$entreprise->setCourrielEntreprise($courriel);
			
		$entreprise->setAdresseEntreprise($adresse);
		$entreprise->setLocalEntreprise($appt);
		$entreprise->setVilleEntreprise($ville);
		$entreprise->setProvinceEntreprise($province);
		$entreprise->setCpostalEntreprise($codePostal);
		$entreprise->setUtilEntreprise(0);
		
		$ticket = new Ticket();
		$ticket->setNomTicket($nomTicket);
		$ticket->setDescriptionTicket($description);
		$ticket->setTravauxTicket($travail);
		$ticket->setIdParentEntreprise($entrepriseCouranteSession);
		
		
		
		
		$date = new DateTime();
		$timeStamp = $date->getTimestamp();
		date_default_timezone_set('America/New_York');
		
		$ticket->setTimestampTicket(date('Y-m-d H:i:s'));	
		
		
		if($idEntreprise != -1){
			$entrepriseSingle = $entrepriseRepo->findOneByidEntreprise($idEntreprise);
		}else{
			
			
			$em2 = $this->getDoctrine()->getManager();
			$em2->persist($entreprise);
			$em2->flush();
			
			$idEntreprise = $entreprise->getIdEntreprise();
			$entrepriseSingle = $entrepriseRepo->findOneByidEntreprise($idEntreprise);
		}
		
			
		$ticket->setIdEntreprise($entrepriseSingle);
		
		$ticket->setIdAgent($agent);
		
		$ticket->setIdEtatTicket($etat);
		

		
		$em = $this->getDoctrine()->getManager();
		$em->persist($ticket);
		$em->flush();
		

    return new Response($idEntreprise);
	}

**Comment by alordmg** [comment]
THANKS ça marche.

:+1:
