### ISSUE TITLE
Ajout du CSS à la page connexion

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#31]
@fREkk C'est quel fichier Twig qui gère le HTML de la page connexion ?

Tout ce que j'ai mit dans le fichier connexion.html.twig apparaît pas :/

Merci

**Comment by fREkk** [comment]
Je sais pas par coeur, mais je sais que le module de connexion est gèrer par userBundle et non dispatcherBundle, regarde dans les views de ce bundle la, si t'as pas trouvé jvais regarder quand j'arrive tentôt!

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Je suis allé voir userBundle et je ne trouve pas de views à l'intérieur. J'ai fait le tour rapidement de tout les dossier et j'ai pas trouvé...

Dans le DefaultController y'a ça : 

```php
public function indexAction(){

        $request = $this->getRequest();
        $session = $request->getSession();

        // get the login error if there is one
        if ( $request->attributes->has( SecurityContext::AUTHENTICATION_ERROR )) {
            $error = $request->attributes->get(SecurityContext::AUTHENTICATION_ERROR);

        } else {
            $error = $session->get(SecurityContext::AUTHENTICATION_ERROR);
            $session->remove(SecurityContext::AUTHENTICATION_ERROR);
        }

        return $this->render('dispatcherBundle:Default:connexion.html.twig', array(
            // last username entered by the user
            'last_username' => $session->get(SecurityContext::LAST_USERNAME),
            'error'         => $error,
        ));
	}
```

Le lien pointe vraiment vers : ```dispatcherBundle:Default:connexion.html.twig``` pourtant c'est pas ça qui est affiché...

**Comment by fREkk** [comment]
Le template est la
: Dispatcher\vendor\friendsofsymfony\user-bundle\Resources\views\Security\login.html.twig

Par contre, si tu veux overwrider ça ya des tutos sur le net pour ramener
ça dans le bundle, mais c'est un peu complexe. À toi de voir.

Si tu veux rechercher des tutos recherche genre FOSUser registration
template ou quelque chose dans le genre. FOS = Friends of symfony au cas ou
tu le savais pas.
