### ISSUE TITLE
Impossible d'afficher les tickets si un ticket ne contient pas de nomEntreprise

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#34]
Après avoir ajouté un ticket qui contient seulement un nom, description et travaux, j'obtiens cette erreur.

```
Impossible to access an attribute ("nomEntreprise") on a NULL variable ("") in dispatcherBundle:Default:liste_ticket.html.twig at line 38
```

À quel endroit je dois permettre une valeur null pour éviter que l'erreur apparaisse ?

J'ai essayer de mettre : 

```
<td>{% if ticket.entreprise.nomEntreprise is not null %} {{ ticket.entreprise.nomEntreprise }} {% endif %}</td>
```

Mais ça ne fonctionne pas.

@fREkk j'aurais besoin de toi pour celle là.

**Comment by alordmg** [comment]
Ça se peut tu que ```ticket.entreprise.nomEntreprise``` soit pas bon ? Je suis pas sûr de savoir ce que je devrais mettre à la place.

**Comment by fREkk** [comment]
Parce qu'un ticket avec seulement un nom ne devrait pas exister, il faut faire ´es validation en JS pour ne pas que ça arrive.

Envoyé de mon iPhone

**Comment by fREkk** [comment]
Jvien de me rendre compte que jai vraiment pas repondu a ta question. Cest dans la bd qui faut que tu mettes ton champs a null si je me trompe pas!

Envoyé de mon iPhone
