### ISSUE TITLE
Envoi des courriels

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#36]
Il faut créer une adresse courriel avec Gmail et configurer le serveur SMTP dans l'application.

**Comment by fREkk** [comment]
Je t'ai parler sur fb concernant ce probleme.

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Ouais non c'est chill j'avais compris.

L'inconvénient de faire un server mail sur mon hébergement c'est qu'il faut que je me procure un certificat qui va faire en sorte que les messages envoyés tombent pas automatiquement dans le SPAM des destinataires.

En passant par Gmail c'est plus fiable.

**Comment by fREkk** [comment]
Template : email.html.twig
Changer le style de la liste déroulante.
