### ISSUE TITLE
Enregistrement d'un nouvel utilisateur retourne erreur 500

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#39]
J'ai été à cette adresse : ```http://45.55.153.230/app.php/register/```

J'ai saisi toutes les infos et ça m'a retourné : 

![capture d ecran 2015-04-23 a 9 55 10 am](https://cloud.githubusercontent.com/assets/11218493/7298629/d7aceb12-e99e-11e4-9809-da3e5795b95a.png)

**Comment by fREkk** [comment]
J'ai créer une registration custom : 45.55.153.230/app_dev.php/ajouterUser

Reste a gèrer la validation en JS.

**Comment by alordmg** [comment]
À quoi sert le dropdown agent dans la page d'inscription?

**Comment by fREkk** [comment]
Pour linker l'agent et ses tickets avec un compte.

Pour que quand l'agent se connecte avec ses infos(user) ben ça y montre juste ses tickets .. jsais pas si tu comptends?

Envoyé de mon iPhone

**Comment by alordmg** [comment]
En vrai man, quand on y pense, c'est pas tout à fait une page d'inscription qui nous faut, c'est d'ajouter un champ nom d'utilisateur et mot de passe à la page créer un agent!

Comprends-tu ce que je veux dire ?

Je vais ajouter les champs dans le template, peux tu te charger d'ajouter le call AJAX ?

**Comment by fREkk** [comment]
non ça marche pas. A moins que tu veuilles que ce soit pas secure. Le userBundle encrypte les Pws

Envoyé de mon iPhone

**Comment by alordmg** [comment]
C'est vraiment impossible de le faire dans cette page là ? :confused:

Honnêtement j'pense ça serait vraiment mieux dans cette page là, étant donné que c'est le but de la page hahaha j'comprend pas comment j'ai fait pour ne pas flasher avant...

Si tu me dis que c'est vraiiiment pas sécuritaire/impossible à ajouter dans la page, je pense pas que ça soit une bonne idée dans ce cas.

**Comment by fREkk** [comment]
Ben j'y avant penser avant, mais cest comme 2 fonctionnalites differentes, don une qu'on a pas developper. Mek on mette a jour ça va peter.

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Okay... j'suis pas sûr de comprendre ce que tu veux dire concernant les mises à jour par contre.

Donc je comprend que c'est pas possible de simplement modifier légèrement le controleur pour permettre l'inscription d'un nouvel agent ? Je comprends pas trop comment tu procède pour ajouter un utilisateur avec Symfony...

**Comment by fREkk** [comment]
C'est que tout le module de connexion est faite pour marcher avec un modele user et non le modele agents. Le bundle gere plein de truc denryption.

Je repense à mon affaire pis chte redit ça, peut-être que ça peux marcher. Genre creer le user en meme temps que l'agent?

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Okay j'ai été voir le code JS de la soumission du formulaire pour ajouter un nouvel agent mais même après mes corrections ça ne fonctionne pas.

J'ai pas le temps de retravailler là dessus aujourd'hui. Je me suis excusé à Pier-Luc et on a jusqu'à lundi pour régler tout ça.

Pourrais-tu prendre quelques minutes pour regarder ça s'il te plait?

Lundi faut que ça soit 100% fonctionnel/coulé dans le béton/on y touche plus on en parle plus.

**Comment by fREkk** [comment]
Comme je t'ai dit en début de semaine, j'ai d'autres projets de commencés, donc plus ou moins le temps de touché à ça.

J'ai 3 autres projets sur la table qui sont, dans mon cas, plus prioritaire. Jpeux jeter un oeil mais jveux pas repasser des heures l'adessu. 

Ton problème vient du fait que les nom de id ont ete changé, je sais pas pourquoi ça fonctionne pas après? Est-ce que tu te souviens d'avoir changer d'autre choses? As-tu réussi a avoir un alert en JS au click?

Jpeux regarder vite-vite mais comme je te dis jpeux pas passer des heures l'adessu.

Envoyé de mon iPhone

**Comment by alordmg** [comment]
S’correct.

J’ai juste une petite question : comment je fais, dans la page ajouter un utilisateur, pour récupérer l’ID de l’entreprise de l’administrateur actuellement connecté ?

j’ai essayé entreprise.idEntreprise et ça fonctionne pas.

Exemple, je suis connecté au nom de alordmg et mon compte faire parti de l’entreprise Les Mauvais Garçons. J’ajoute un nouvel agent pour mon entreprise, alors il faudrait que l’ID d’entreprise de l’agent que je créé soit le même que celui des Mauvais Garçons.

 <http://lesmauvaisgarcons.ca/>
 <http://lesmauvaisgarcons.ca/>

**Comment by alordmg** [comment]
J'ai fermé la issue par erreur :\

**Comment by fREkk** [comment]
Comme ça :

$idEntreprise = $this->getUser()->getIdEntreprise();

2015-05-08 14:36 GMT-04:00 Antoine Lord <notifications@github.com>:

**Comment by alordmg** [comment]
Salut @fREkk ,

J'suis encore sur l'histoire d'ajout d'utilisateur. Y'a pu d'erreur 500 mais ce qui arrive c'est qu'une fois connecté avec le nouvel utilisateur, j'ai une erreur comme quoi l'IdAgent est manquant.

Ce que je remarque, c'est que la méthode dans le controlleur n'indique pas de nouvel IdAgent, donc il ne s'inscrit pas dans la BD dans la table dispatcher_user.

Comment je fais pour que dès l'ajout d'un nouveau User, son ID créé dans la table user s'ajoute en même temps dans la table dispatcher_user ?

Hésite pas à m'apeller au 581-984-2842 si tu veux plus de détails. Si t'as 15 minutes pour m'aider ça faire ça, ça serait ben apprécié parce que c'est hyper urgent.

Thanks man

**Comment by fREkk** [comment]
Salut! 

Pour pouvoir avoir le dernier Id (celui que tu viens d'ajouter dans la bd), regarde le lien :

http://stackoverflow.com/questions/3509350/get-the-last-insert-id-with-doctrine-2

En gros apres le "flush" de ton premier insert t'apelles ta methode pour aller chercher ton ID, avec aucun argument et ça devrait le faire.

Redonne moi les acces/ infos de connexion et je regarde ça quand j'ai 2 secondes!

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Merci Francis! Je check ça en ce moment.

Voici le code actuel de la fonction : 

``` php
public function ajouterUserAjaxAction(){

    $userManager = $this->container->get('fos_user.user_manager');

    $userAdmin = $userManager->createUser();

    $request = $this->get('request');

    $username = $request->query->get('username');
    $password = $request->query->get('password');
    $email = $request->query->get('email');
    $idEntreprise = $this->getUser()->getIdEntreprise();
    $idAgent= $request->query->get('idAgent');


    $userAdmin->setUsername($username);
    $userAdmin->setEmail($email);
    $userAdmin->setPlainPassword($password);
    $userAdmin->setEnabled(true);

    $entrepriseRepo = $this->getDoctrine()
    ->getRepository('UserBundle:Entreprise');

    $entreprise = $entrepriseRepo->findOneByidEntreprise($idEntreprise);

    $agentRepo = $this->getDoctrine()
    ->getRepository('UserBundle:Agent');

    $agent = $agentRepo->findOneByidAgent($idAgent);

    $userAdmin->setIdEntreprise($idEntreprise);
    $userAdmin->setIdAgent($agent);

    $userManager->updateUser($userAdmin, true);

    return new Response ('Utilisateur ajouté');
}
```

J'ai l'impression que le problème est à la ligne ```$idAgent= $request->query->get('idAgent');```

De ce que je comprend de cette ligne, c'est qu'elle récupère le idAgent qui lui a été envoyé en GET avec Ajax. Le problème, c'est que le call Ajax contient de pas idAgent. Il faudrait donc que je remplace cette ligne par : 

``` php
$em->persist($user);
$em->flush();
$user->getId();
```

?

Je suis pas sûr de savoir où placer ces trois lignes de code dans la fonction existante dans le contrôleur.

Accès au staging (tout ce que tu change là dessus va être overwrite par Git! Oublie pas de m'envoyer le code ou de le push par toi-même!)

IP : 45.55.153.230
User : root
Pass : c%W3>z8VcM

Merci infiniment pour ton support.

**Comment by fREkk** [comment]
Pour voir si ton problème est vraiment la, remplace le IdAgent par un index qui existe dans ta BD.

Envoyé de mon iPhone

**Comment by alordmg** [comment]
C'est confirmé le problème vient de là! J'ai mi un Id d'un agent existant et le login se fait sans faute.

**Comment by fREkk** [comment]
Dans le fond, cette ligne la : $idAgent= $request->query->get('idAgent');
Est sensée aller chercher le dernier enregistrement de la table agent, mais
j'ai jamais eu a faire ça avant. Donc ça se peux que ça marche juste pas.
Regarde sur le net pour trouver une facon de sortir la derniere occurence
d'un modele.

Mais dans le formulaire y'avait pas un dropdown avec tout les agents pour
qu'on sélectionne celui qu'on veut ajouter genre? Jsais pas messemble que
c'est wierd, il manque dekoi. Je crois que le Ajax appelle deux fonctions
une après l'autre (une qui créer l'agent et l'autre qui créer la user).
Donc en allant chercher la derniere occurence d'agent dans la BD ça devrait
le faire!

2015-05-25 10:17 GMT-04:00 Antoine Lord <notifications@github.com>:

**Comment by alordmg** [comment]
Ben pour le formulaire, c'est que ça a pas de sens de sélectionner l'agent dans un dropdown alors qu'on est justement dans la page pour le créer. Normalement, à la création d'un agent, ça crée du même coup un utilisateur de Dispatcher avec les mêmes logins et tout.

Effectivement, la fonction JS fait deux call Ajax : 

1. Le premier pour créer l'agent dans la table Agents
2. Le deuxième pour ajouter l'agent créé dans la table dispatcher_user.

Ce qu'il faut, c'est que le 2e call Ajax envoi le ID de l'agent qui vient juste d'être créé. Sauf que je sais pas comment récupérer le ID qui vient d'être créé directement dans le JS. Est-ce qu'il y a moyen de retourner le ID qui vient juste d'être créé directement dans le JS ? Je pourrais stocker dans une variable et l'envoyer dans le 2e call Ajax. 

Est-ce que tu me suis ? Si tu veux m'appeler n'hésite pas.

**Comment by alordmg** [comment]
J'voulais essayer d'ajouter ce code là : 

``` php
$em->persist($user);
$em->flush();
$user->getId();
```

Mais il dit d'ajouter ça après le premier flush, et il n'y en a juste pas dans la fonction...

**Comment by fREkk** [comment]
Cest dans ton autre fonction faut croire, celle qui ajoute l'agent et non le user

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Ouin mais tu comprends que c'est quand j'ajoute le **user** qui faut que je stocke le nouvel ID de l'agent. Ça s'ajoute déjà quand je crée l'agent.

**Faut ABSOLUMENT que ça soit réglé AUJOURD'HUI.**

**Option A :** Aller pogner le dernier ID ajouté et l'envoyer dans ajouterUserAjaxAction() mais vu que y'a pas de flush j'sais pas comment le pogner.

**Option B :** Pogner le ID du dernier agent ajouté en JS et l'envoyer au controlleur en Ajax. Sauf que je suis pas sûr de savoir comment créer une nouvelle route et une nouvelle fonction dans le contrôleur qui recherche le dernier agent ajouté.

Faut juste mettre dequoi en ligne aujourd'hui qui FONCTIONNE pis ensuite le client s'arrangera avec ses troubles. Sorry man mais là faut absolument qu'on règle ça au plus vite. Ça fait déjà genre 1 mois que c'est supposé être final pis ça marche pas encore. J'comprend tellement quedalle à Symfony et j'suis tellement chargé ces temps-ci que j'ai juste pas le temps.

**Comment by fREkk** [comment]
Salut,

Tout ce que t'as a faire cest retrouver la derniere occurence dans ta bd. Jpeux regarder en 15mins durant mon dinner mais jgarantie pas que ça va etre reglé.

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Ça m’aiderais beaucoup parce que j’sais pas trop où m’enligner.

 <http://lesmauvaisgarcons.ca/>
 <http://lesmauvaisgarcons.ca/>

**Comment by fREkk** [comment]
C'est quoi l'URL de création de user ?

**Comment by alordmg** [comment]
ajouterUser/Ajax

C’est ça que tu veux dire ?

 <http://lesmauvaisgarcons.ca/>
 <http://lesmauvaisgarcons.ca/>

**Comment by fREkk** [comment]
Tes fichiers sont tu compiler? Jfais des modifs dans le main.js pis sa
marche pas.

Comme je t'ai dit. Dans la fonction ajouterAgentAjaxAction du controller,
elle retourne le dernier ID. Donc tout ce que tu as a faire c'est trapper
la reponse du call ajax comme ça:

 .always(function(data) {
    $('idduchampidagentdetapage').val(data);
  })



(Wtf @ la couleur laide qui reste.)

Ensuite avec ton autre call ajax tu décommentes les autres lignes de
idAgent et tu passe idAgent comme argument a ta deuxieme fonction, pis
tu l'ajoute normalement.

**Comment by fREkk** [comment]
.done(function(data) {
    $('idduchampidagentdetapage').val(data);
  })


Done pas always scuse.

**Comment by alordmg** [comment]
> Tes fichiers sont tu compiler? Jfais des modifs dans le main.js pis sa
marche pas.

Si tu travaille avec app_dev.php ça devrait prendre effet.

J'ai ajouté la ligne que tu m'a shooté : 

``` php
.done(function(data) {
    $('idAgent').val(data);
  })
```

Ma console me retourne que la fonction .done existe pas :(

``` php
$.ajax({
    url: "agent/ajax",
    data: {
        prenom : prenomAgent,
        nom : nomAgent,
        telephone : telephoneAgent,
        courriel : courrielAgent,
        note : notesAgent
    }.done(function(data){
        $('#idAgent').val(data);
    }),
    context: document.body,
    method: 'POST',
})
```

**Comment by alordmg** [comment]
Stu une dépendance JS que j'aurais enlevé ?

**Comment by fREkk** [comment]
Parce que faut pas que t'as mette la, tcheke dans les autre call ajax ya des .done de caller deja.

Ensuite regarde pour savoir ce que data te donne (fait un alert en attendant), si ça te retourne un id, t'es en buisness.

Et ouais, je crois que c'est en changeant des choses que sa pu fucker. Parce que la mecanique est encore la.


Envoyé de mon iPhone
