### ISSUE TITLE
Un agent ne peut pas modifier le ticket

### ISSUE THREAD

**Issue by alordmg** [alordmg/dispatcher#46]
Salut @fREkk 

Un bug de corrigé, 10 de retrouvés...

1. Côté admin, je crée un agent;
2. Je lui attribue un ticket;
3. Je me connecte avec le compte de l'agent créé;
4. Je check la liste des tickets : il n'y a pas de bouton Modifier pour changer le statut du ticket;

Dans le code deu template, je retrouve ceci : 

```
{% if is_granted('ROLE_ADMIN') %}<td class="text-center"><a href="{{ path('modifTicket', {'id':ticket.ticket.idTicket})}}" class="button tiny round">Modifier</a></td>{% endif %}
```

Comment je fait pour ajouter en Twig un truc du genre : 

Si je suis **Admin** OU **l'agent à qui le ticket est assigné** = afficher le bouton Modifier ?

Évidemment, il faut que l'agent puisse changer le statut de chaque ticket qui lui est attribué, c'est le but de l'application!

**Comment by fREkk** [comment]
Ben en fait, t'as juste à enlever le is-Granted, avant tout les tickets s'affichaient, mais la seulement ceux de l'Utilisateur courant donc plus besoin de faire cette verification!

Envoyé de mon iPhone

**Comment by alordmg** [comment]
Très bonne idée!

J’ai enlevé la validation et quand je clique sur Modifier, ça me donne une erreur Access Denied.

Ça s’peut tu que tu check dans la page Modifier ticket si c’est un Admin ou un Agent et que tu rejete les Agents ?


 <http://lesmauvaisgarcons.ca/>
 <http://lesmauvaisgarcons.ca/>

**Comment by fREkk** [comment]
ouais exactement
App/config/security si jmentrompe pas


Envoyé de mon iPhone

**Comment by alordmg** [comment]
Okay je met tu juste : 

```
- { path: ^/modifier, role: IS_AUTHENTICATED }
```

?

**Comment by alordmg** [comment]
Réussi. C'était : 

``` ROLE_NONUSER ```

**Comment by fREkk** [comment]
Good!


Envoyé de mon iPhone
